// Auto-generated by scripts/generate-collage-manifest.mjs
// Do not edit by hand.
window.__COLLAGE_IMAGES__ = [
  "images/collage/1.jpg",
  "images/collage/2.jpg",
  "images/collage/3.jpg",
  "images/collage/4.jpg",
  "images/collage/5.jpg",
  "images/collage/6.jpg",
  "images/collage/7.jpg",
  "images/collage/8.jpg",
  "images/collage/9.jpg",
  "images/collage/10.jpg",
  "images/collage/11.jpg",
  "images/collage/12.jpg",
  "images/collage/13.jpg",
  "images/collage/14.jpg",
  "images/collage/15.jpg",
  "images/collage/16.jpg",
  "images/collage/image-01.jpg"
];
